---
- name: install firewalld service
  hosts: db
  become: yes
  tasks: 
  - name: install firewalld
    yum:
      name: firewalld
      state: present

  - name: start firewall service
    service: 
      name: firewalld
      state: started    
