---
- name: Installing htpd service on the server
  hosts: localhost
  connection: local
  tasks: 
  - name: installing httpd
    yum:
       name: httpd
       state: present

  - name: Starting httpd service
    service: 
       name: httpd
       state: started


       

