---
- name: Playbook to launch resources
  hosts: localhost
  connection: local
  tasks:
  - name: read the csv file
    read_csv:
     path: aws_resources.csv
    register: aws_list
    delegate_to: localhost
  - debug:
     msg: "{{ aws_list.list[0].key_name }}"

  - name: Create a new EC2 key pair
    ec2_key:
     name: "{{ aws_list.list[0].key_name }}"
     region: "{{ aws_list.list[0].region }}"
    register: ec2_key
  - name: Save private key
    copy: 
     content: "{{ ec2_key.key.private_key }}" 
     dest: ./{{ aws_list.list[0].key_name }}.pem
     mode: "400"
    when: ec2_key.changed  

  - name: launch 1st ec2
    ec2:
     image: "{{ aws_list.list[0].ami_id }}"
     group: "{{ aws_list.list[0].sg }}"
     vpc_subnet_id: "{{ aws_list.list[0].subnet }}"
     instance_type: "{{ aws_list.list[0].instance_type }}"
     count: 1
     region: "{{ aws_list.list[0].region }}"
     key_name: "{{ aws_list.list[0].key_name }}"
     instance_tags:
        Name: EC2_Node1
        Env: Dev
    register: instance_status

  - debug: 
      msg: "{{ instance_status.instances[0].id }}" 
