---
- name: Hosts reachablity test
  hosts: tag_Nmae_chef
  tasks:
  - name: check ping pong
    ping:
    register: ping_status

  - name: print ping status
    debug:
            msg: "{{ ping_status }}"    
