---
- name: Install base packages
  yum: name={{ item }} state=installed
  with_items:
    - ntp
    - git
    - python-pip
    - python3-pip
  tags:
    - packages- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
